# Generated by Django 5.1.4 on 2024-12-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
